kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: angelfreak/docker-ssg
    tags:
    - latest
    - '4'
    - '4.0'
