kind: pipeline
name: default

steps:
- name: ssg5-build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: angelfreak/docker-ssg
    tags:
    - latest
    - '5'
    - '5.0'
    - '5.0.0'
    dockerfile: Dockerfile
